/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_constants.h"

namespace Test {

const proxyConstants g_proxy_constants;

proxyConstants::proxyConstants() {
}

} // namespace

